language: go

go:
  - "1.14.x"

services:
  - docker

branches:
  only:
    - master
    - /^release-[0-9]+\..*$/

addons:
  sonarcloud:
    organization: "open-cluster-management"
    token:
      secure: "GDwcEouX35WwwS01FH0t6hoVrkZGvBmHd3l4Y1s5LKZ60pM95W4pkuaDqez/ilYQxTIVwVxJvcwpnWqP/BdisbHiLPNfTSl/4KEa9TsYigWKjb4h772SIPexuUzeW+mHHC4hYVhCqa6f4gPRppumLCEVFVBCmKDRlARnuZs2l2gdEf27Xgh9VRhP+khGQKxtczbZM/+Wa6KZk9U8MJFg2xVPUbl6K+/BAZQ51oS7u9jb+A1X/CBwIO8wBJeDvpODTAfGamEHCqppqFLLX3waj8s8A56jGODYlw4v0TRLVldDMIcKXgBF6cOh20lhNm8YKV9mPf11yMFQ97heEftz4KOQvu91OUO2fk5fUpopG8+jQngcAVGMFb62rIVTuyyoN7O1FQrnNTmB67E/T+9YeRZdQEXJoDDU73LNnkRYWK6lEGQhugl9Ogr/Ba0I2esnSsfYBcGBY7Jae90+cLD54pORhOhDXpQTJyc2KD85BbZqSOgIJ1A4wIbOXCd0hit8wtMNj/RTEP7NaPD4/lJJyukKgChp3QJ0+oabCe2kjRztfw+yqRrD79DYgFYP3Tlx9Wv+PrkANTeNDs/uyK7EQ8gCgdK/TEKlqXmBk6kkLDrrLFvw5ukEOjfSHNLPYbWARfbfPW+bBdwLlRWx0E45FNZHtJu4s1rl5qXe+Gvpteg="
env:
  global:
    # Required
    - OS=linux
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"
    # Component Specific
    - COMPONENT_INIT_COMMAND=${TRAVIS_BUILD_DIR}/build/install-dependencies.sh
    - COMPONENT_BUILD_COMMAND=${TRAVIS_BUILD_DIR}/build/build.sh
    - COMPONENT_UNIT_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-unit-tests.sh
    - COMPONENT_E2E_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-e2e-tests.sh

stages:
  # - lint
  - build
  - unit-test
  - test-e2e
  - publish

jobs:
  include:
    # - stage: lint
    #   name: "Run code lint"
    #   if: type = pull_request
    #   script: bash ${TRAVIS_BUILD_DIR}/build/run-code-lint.sh
    - stage: build
      name: "Build the image and push it"
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - make copyright-check TRAVIS_BRANCH=${TRAVIS_BRANCH}
        - |
          make
          make component/build
          make component/push
          if [ "$IMAGE_SCAN" != "false" ]; then make security/scans; fi;
        - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "release-2.2" ]; then 
            export COMPONENT_NEWTAG="latest-2.2";
            make component/tag;
            export COMPONENT_VERSION="latest";
            export COMPONENT_TAG_EXTENSION="-2.2";
            make component/push;
          fi;
    - stage: unit-test
      name: "Run unit test"
      script:
        - set -e
        # Set the image tag differently for PRs
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        # Bootstrap the build harness, pull test image, and run unit tests.
        - |
          make
          make component/test/unit
        - |
          set +e
          make stop-instrumented  
          set -e
          make coverage-merge
          make go/gosec-install
          gosec -fmt sonarqube -out gosec.json -no-fail ./...
          make sonar/js
    - stage: test-e2e
      name: "Deploy the image to a cluster and run e2e tests"
      if: type = pull_request
      script:
        #Check out a clusterpool, set up oc, deploy, run e2e tests, and return clusterpool cluster
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - |
          make
          make component/pull
          make component/test/e2e
    - stage: publish
      name: "Publish the image to quay with an official version/sha tag and publish entry to integration pipeline stage"
      if: type = push AND branch =~ /^release-[0-9]+\..*$/
      script:
        - |
          make
          make pipeline-manifest/update PIPELINE_MANIFEST_COMPONENT_SHA256=${TRAVIS_COMMIT} PIPELINE_MANIFEST_COMPONENT_REPO=${TRAVIS_REPO_SLUG} PIPELINE_MANIFEST_BRANCH=${TRAVIS_BRANCH}