#
# Build and push a docker image of the build harness and extensions
#
os:
  - linux

language: python
python: "3.7"

services:
  - docker

env:
  global:
    # Required
    - OS=linux

stages:
  - build

jobs:
  include:
    - stage: build
      name: "Build the image and push it"
      script:
        - |
          docker build --tag quay.io/stolostron/build-harness:latest .
          docker login quay.io/open-cluster-management -u ${DOCKER_USER} -p ${DOCKER_PASS}
          docker push quay.io/open-cluster-management/build-harness:latest

