apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
  labels:
    pipelines.appstudio.openshift.io/type: build
  name: config-policy-controller-main-on-push
  namespace: crt-redhat-acm-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/config-policy-controller-acm-217:{{revision}}
    - name: dockerfile
      value: build/Dockerfile.rhtap
    - name: image-expires-after
      value: 21d
    - name: prefetch-input
      value: '[{"type": "gomod", "path": "."}]'
    - name: build-source-image
      value: 'false'
    - name: build-platforms
      value:
        - linux/x86_64
        - linux/arm64
    - name: additional-tags
      value:
        - latest
    - name: skip-checks
      value: 'true'
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/stolostron/konflux-build-catalog.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/common.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-config-policy-controller-acm-217
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
