name: Framework

on:
  pull_request:
    branches:
      - main
      - release-[0-9]+.[0-9]+

jobs:
  fw-kind-tests:
    name: KinD
    uses: stolostron/governance-policy-framework/.github/workflows/kind.yml@b3abb22588a2a728730e411dab96cd79eda8e602 # main
