name: Framework

on:
  pull_request:
    branches:
      - main
      - release-[0-9]+.[0-9]+

jobs:
  fw-kind-tests:
    name: KinD
    uses: stolostron/governance-policy-framework/.github/workflows/kind.yml@dedb66750d308ddc111793f6e418ddc2f738393a # main
