name: KinD tests

on:
  push:
    branches:
      - main
      - release-2.[3-9]
  pull_request:
    branches:
      - main
      - release-2.[3-9]

defaults:
  run:
    shell: bash
    working-directory: config-policy-controller

jobs:
  kind-tests:
    runs-on: ubuntu-latest
    env:
      REGISTRY: localhost:5000
    strategy:
      matrix:
        # Run tests on oldest and newest supported OCP Kubernetes
        # - OCP 4.5 runs Kubernetes v1.18
        # KinD tags: https://hub.docker.com/r/kindest/node/tags
        kind:
          - 'v1.18.15'
          - 'latest'
    name: KinD tests
    steps:
    - name: Checkout Config Policy Controller
      uses: actions/checkout@v2
      with:
        path: config-policy-controller
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Temp
      run: |
        cat <<EOF > event.json
        ${{ toJSON(github.event) }}
        EOF
        mv temp-coverage.out coverage.out
        mv temp-gosec.json gosec.json

    - name: Store the GitHub triggering event for the sonarcloud workflow
      if: |
        matrix.kind == 'latest' &&
        github.repository_owner == 'stolostron'
      run: |
        cat <<EOF > event.json
        ${{ toJSON(github.event) }}
        EOF

    - name: Upload artifacts for the sonarcloud workflow
      if: |
        matrix.kind == 'latest' &&
        github.repository_owner == 'stolostron'
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          config-policy-controller/coverage*.out
          config-policy-controller/event.json
          config-policy-controller/gosec.json
