name: KinD tests

on:
  push:
    branches:
      - main
      - release-2.[3-9]
  pull_request:
    branches:
      - main
      - release-2.[3-9]

defaults:
  run:
    shell: bash
    working-directory: config-policy-controller

jobs:
  kind-tests:
    runs-on: ubuntu-latest
    env:
      REGISTRY: localhost:5000
    strategy:
      matrix:
        # Run tests on oldest and newest supported OCP Kubernetes
        # - OCP 4.5 runs Kubernetes v1.18
        # KinD tags: https://hub.docker.com/r/kindest/node/tags
        kind:
          - 'v1.18.15'
          - 'latest'
    name: KinD tests
    steps:
    - name: Checkout Config Policy Controller
      uses: actions/checkout@v2
      with:
        path: config-policy-controller
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: config-policy-controller/go.mod

    - name: Verify modules
      run: |
        go mod verify

    - name: Verify format
      run: |
        make fmt
        git diff --exit-code
        make lint

    - name: Verify deploy/operator.yaml
      run: |
        make generate-operator-yaml
        git diff --exit-code

    - name: Unit and Integration Tests
      run: |
        make test

    - name: Create K8s KinD Cluster - ${{ matrix.kind }}
      env:
        KIND_VERSION: ${{ matrix.kind }}
      run: |
        make kind-bootstrap-cluster-dev

    - name: E2E Tests
      run: |
        export GOPATH=$(go env GOPATH)
        make e2e-test-coverage

    - name: Create K8s KinD Cluster to simulate hosted mode - ${{ matrix.kind }}
      env:
        KIND_VERSION: ${{ matrix.kind }}
      run: |
        make kind-additional-cluster

    - name: E2E tests that simulate hosted mode
      run: |
        export GOPATH=$(go env GOPATH)
        make e2e-test-hosted-mode-coverage

    - name: Test Coverage Verification
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        make test-coverage
        make coverage-verify

    - name: Test Coverage and Report Generation
      run: |
        make test-coverage | tee report_unit.json
        make gosec-scan
        cat gosec.json

    - name: SonarCloud Analysis
      if: |
        matrix.kind == 'latest' &&
        github.repository_owner == 'stolostron' &&
        (github.event_name == 'push' || github.event_name == 'pull_request')
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: config-policy-controller
        args: >
          --debug

    - name: Debug
      if: ${{ failure() }}
      run: |
        make e2e-debug

    - name: Clean up cluster
      if: ${{ always() }}
      run: |
        make kind-delete-cluster
