name: Sonarcloud scan

on:
  workflow_run:
    workflows:
      - KinD tests
    types:
      - completed

jobs:
  sonarcloud:
    uses: stolostron/governance-policy-framework/.github/workflows/sonarcloud.yml@3f6b15d8426304e337bd7b93efe8fd09873f1cee # main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
