name: Sonarcloud scan

on:
  workflow_run:
    workflows:
      - KinD tests
    types:
      - completed

jobs:
  sonarcloud:
    uses: stolostron/governance-policy-framework/.github/workflows/sonarcloud.yml@dedb66750d308ddc111793f6e418ddc2f738393a # main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
