name: Sonarcloud scan

on:
  workflow_run:
    workflows:
      - KinD tests
    types:
      - completed

jobs:
  sonarcloud:
    uses: stolostron/governance-policy-framework/.github/workflows/sonarcloud.yml@b3abb22588a2a728730e411dab96cd79eda8e602 # main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
